name: lumet_frontend

services:
  lumet_frontend:
    image: lumet_frontend_image
    build: .
    container_name: lumet_frontend_container
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - lumet_frontend_node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  lumet_frontend_node_modules:
    name: lumet_frontend_node_modules_volume
