export const FILAS_POR_PAGINA = 8;

export const CLIENTES_INICIAL = [
  { id: 1, nombre: 'Ana López', telefono: '+1 123 456 789', correo: 'ana@empresa.com', vendedor: 'Eduardo Magno', estado: 'Venta completada' },
  { id: 2, nombre: 'Carlos Martinez', telefono: '+1 957 321 654', correo: 'carlos@empresa.com', vendedor: 'María López', estado: 'Venta cancelada' },
  { id: 3, nombre: 'Empresa ABC', telefono: '+1 444 555 886', correo: 'contacto@empresaabc.com', vendedor: 'Eduardo Magno', estado: 'Venta pospuesta' },
  { id: 4, nombre: 'Grupo Sigma', telefono: '+1 653 222 111', correo: 'info@gruposigma.com', vendedor: 'Pedro Sánchez', estado: 'Venta pendiente' },
  { id: 5, nombre: 'María García', telefono: '+1 555 111 222', correo: 'maria@empresa.com', vendedor: 'Eduardo Magno', estado: 'Venta completada' },
  { id: 6, nombre: 'Luis Fernández', telefono: '+1 555 333 444', correo: 'luis@empresa.com', vendedor: 'María López', estado: 'Venta cancelada' },
  { id: 7, nombre: 'Tech Solutions', telefono: '+1 555 666 777', correo: 'contacto@techsol.com', vendedor: 'Pedro Sánchez', estado: 'Venta pospuesta' },
  { id: 8, nombre: 'Laura Pérez', telefono: '+1 555 888 999', correo: 'laura@empresa.com', vendedor: 'Eduardo Magno', estado: 'Venta pendiente' },
  { id: 9, nombre: 'Roberto Díaz', telefono: '+1 555 000 111', correo: 'roberto@empresa.com', vendedor: 'María López', estado: 'Venta completada' },
  { id: 10, nombre: 'Consultores SA', telefono: '+1 555 222 333', correo: 'info@consultores.com', vendedor: 'Pedro Sánchez', estado: 'Venta cancelada' },
  { id: 11, nombre: 'Sofia Ruiz', telefono: '+1 555 444 555', correo: 'sofia@empresa.com', vendedor: 'Eduardo Magno', estado: 'Venta pospuesta' },
  { id: 12, nombre: 'Andrés Mora', telefono: '+1 555 666 777', correo: 'andres@empresa.com', vendedor: 'María López', estado: 'Venta pendiente' },
  { id: 13, nombre: 'Inversiones XYZ', telefono: '+1 555 888 000', correo: 'contacto@inversiones.com', vendedor: 'Pedro Sánchez', estado: 'Venta completada' },
  { id: 14, nombre: 'Carmen Soto', telefono: '+1 555 111 222', correo: 'carmen@empresa.com', vendedor: 'Eduardo Magno', estado: 'Venta cancelada' },
  { id: 15, nombre: 'Diego Reyes', telefono: '+1 555 333 444', correo: 'diego@empresa.com', vendedor: 'María López', estado: 'Venta pospuesta' },
  { id: 16, nombre: 'Logística Global', telefono: '+1 555 555 666', correo: 'info@logistica.com', vendedor: 'Pedro Sánchez', estado: 'Venta pendiente' },
  { id: 17, nombre: 'Elena Vega', telefono: '+1 555 777 888', correo: 'elena@empresa.com', vendedor: 'Eduardo Magno', estado: 'Venta completada' },
  { id: 18, nombre: 'Javier López', telefono: '+1 555 999 000', correo: 'javier@empresa.com', vendedor: 'María López', estado: 'Venta cancelada' },
  { id: 19, nombre: 'Servicios Pro', telefono: '+1 555 121 212', correo: 'contacto@serviciospro.com', vendedor: 'Pedro Sánchez', estado: 'Venta pospuesta' },
  { id: 20, nombre: 'Patricia Cruz', telefono: '+1 555 343 454', correo: 'patricia@empresa.com', vendedor: 'Eduardo Magno', estado: 'Venta pendiente' },
  { id: 21, nombre: 'Miguel Ángel', telefono: '+1 555 565 676', correo: 'miguel@empresa.com', vendedor: 'María López', estado: 'Venta completada' },
  { id: 22, nombre: 'Marketing Plus', telefono: '+1 555 787 898', correo: 'info@marketingplus.com', vendedor: 'Pedro Sánchez', estado: 'Venta cancelada' },
  { id: 23, nombre: 'Isabel Navarro', telefono: '+1 555 909 010', correo: 'isabel@empresa.com', vendedor: 'Eduardo Magno', estado: 'Venta pospuesta' },
  { id: 24, nombre: 'Francisco Jiménez', telefono: '+1 555 232 434', correo: 'francisco@empresa.com', vendedor: 'María López', estado: 'Venta pendiente' },
  { id: 25, nombre: 'Desarrollo Web SA', telefono: '+1 555 656 878', correo: 'contacto@devweb.com', vendedor: 'Pedro Sánchez', estado: 'Venta completada' },
];
